############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Benefits"
url = "#features"
weight = 2

[[main]]
name = "Channels"
url = "#channels"
weight = 3

[[main]]
name = "Security"
url = "#security"
weight = 4

[[main]]
name = "Contact"
url = "#contact-us"
weight = 5


# Footer menu
[[footer]]
name = "Home"
url = ""
weight = 1

[[footer]]
name = "Contact"
url = "#contact-us"
weight = 2

[[footer]]
name = "Faq"
url = "faq/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4